package:
    type:           yii2-extension
    name:           yii2-menumanager
    title:          DEPRECATED in favour of hiqdev\yii2-menus
    headline:       '[DEPRECATED] Yii2 Menu Manager'
    keywords:       yii2, menu, manager
    namespace:      hiqdev\menumanager
    description:    |
        DEPRECATED in favour of [hiqdev\yii2-menus](https://github.com/hiqdev/yii2-menus)
