package:
    type:           yii2-extension
    name:           yii2-menumanager
    title:          Menu Manager for Yii2
    headline:       Yii2 Menu Manager
    keywords:       yii2, menu, manager
    namespace:      hiqdev\menumanager
    description:    |
        Features planned to provide:

        - auto loading and assembling menus from extensions
        - widgets
