package:
    type:           yii2-extension
    name:           yii2-menumanager
    title:          Menu Manager for Yii2
    headline:       Yii2 Menu Manager
    keywords:       menu, manager, extension, yii2
    namespace:      hiqdev\menumanager
    description:    Menu Manager with auto loading from extension, and widgets

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
